# DX 601 Week 11 Homework

## Introduction

In this homework, you will practice working with systems of linear equations and review previous weeks' material.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [92]:
import math
import sys

In [93]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats
import sklearn.linear_model

## Shared Data

### Vineyard Data

This data set attempts to predict yields for a small vineyard in Lake Erie in 1991 based on the yields in the previous years.
Each row of the data set represents the yields of a row of the vineyard.
See https://github.com/EpistasisLab/pmlb/blob/master/datasets/192_vineyard/metadata.yaml for more information.

In [94]:
vineyard = pd.read_csv("https://github.com/EpistasisLab/pmlb/raw/refs/heads/master/datasets/192_vineyard/192_vineyard.tsv.gz", sep="\t")
vineyard.head()

   lugs_1989  lugs_1990  target
0        1.0        5.0     9.5
1        3.0        8.0    17.5
2        3.0       11.0    18.0
3        3.0        9.0    20.0
4        5.0        9.5    20.5

In [95]:
vineyard_inputs = vineyard[["lugs_1989", "lugs_1990"]]
vineyard_inputs.head()

   lugs_1989  lugs_1990
0        1.0        5.0
1        3.0        8.0
2        3.0       11.0
3        3.0        9.0
4        5.0        9.5

In [96]:
vineyard_target = vineyard["target"]

## Problems

### Problem 1

Set `p1` to the value of $x$ after solving the following system of linear equations.

\begin{array}{rcl}
3x & = & 4.2 \\
\end{array}

In [97]:
# YOUR CHANGES HERE

p1 = 4.2/3

In [98]:
p1

1.4000000000000001

### Problem 2

Set `p2` to be a tuple of `(x, y)` where $x$ and $y$ are the solution to the following system of linear equations.

\begin{array}{rcl}
3x + 2y & = & 8.6 \\
2x + 5y & = & 13.8 \\
\end{array}

Hint: Just do this by hand.

In [99]:
# YOUR CHANGES HERE

p2 = (1.4, 2.2)

In [100]:
p2

(1.4, 2.2)

### Problem 3

Set `p3` to be the x intercept of the following equation.

\begin{array}{rcl}
4x + 2y + 3z & = & 12 \\
\end{array}

In [101]:
# YOUR CHANGES HERE

# where y and z = 0, 4x = 12, x = 3
p3 = 3

In [102]:
p3

3

### Problem 4

Set `p4` to be the sum of the 5 axis intercepts of the following equation.

\begin{array}{rcl}
9a + 4b + 27c + 6d + 3e & = & 36 \\
\end{array}

In [103]:
# YOUR CHANGES HERE

# a = 4, b = 9, c = 4/3, d = 6, e = 12
p4 = 4 + 9 + 4/3 + 6 + 12

In [104]:
p4

32.333333333333336

### Problem 5

Set `p5` to the augmented matrix of the following system of linear equations.

\begin{array}{rcl}
3x + 2y + 13z = 10 \\
7x + 2y - 13z = 23 \\
\end{array}

In [105]:
# YOUR CHANGES HERE

p5 = np.array([[3, 2, 13, 10], [7, 2, -13, 23]])

In [106]:
p5

array([[  3,   2,  13,  10],
       [  7,   2, -13,  23]])

### Problem 6

Set `p6` to the rank of the following system of linear equations?

\begin{array}{rcl}
3x + 2y + 0z = 3 \\
2x + 3y + 1z = 5 \\
5x + 5y + 5z = 20 \\
\end{array}

In [107]:
# YOUR CHANGES HERE

# rank = number of non-zero rows 
p6 = 3

In [108]:
p6

3

### Problem 7

Consider the following system of linear equations.

\begin{array}{rcl}
3x + 2y + 0z = 3 \\
2x + 3y + 1z = 5 \\
5x + 5y + 5z = 20 \\
\end{array}

This system could be rewritten as 
\begin{array}{rcl}
\mathbf{A}
\begin{bmatrix}
x \\ y \\ z \\
\end{bmatrix}
& = &
\begin{bmatrix}
3 \\ 5 \\ 20 \\
\end{bmatrix}
\end{array}

Set `p7` to $\mathbf{A}$.

In [109]:
# YOUR CHANGES HERE

p7 = np.array([[3, 2, 0, ], [2, 3, 1], [5, 5, 5]])

In [110]:
p7

array([[3, 2, 0],
       [2, 3, 1],
       [5, 5, 5]])

### Problem 8

Set `p8` to the number of free variables in the following system of linear equations.

\begin{array}{rcl}
x + 3y + 4z = 3 \\
0x + 0y + 1z = 2 \\
x + 3y + 5z = 5 \\
\end{array}

In [111]:
# YOUR CHANGES HERE

# number of free variables = number rows - rank
p8 = 1

In [112]:
p8

1

### Problem 9

Set `p9` to any solution `(x, y, z)` to the following system of linear equations.

\begin{array}{rcl}
2x + 4y + 0z = 16 \\
1x + 3y + 1z = 16 \\
3x + 0y + 0z = 6 \\
\end{array}

In [113]:
# YOUR CHANGES HERE

p9 = (2, 3, 5)

In [114]:
p9

(2, 3, 5)

### Problem 10

Set `p10` to any solution `(x, y, z)` to the following system of linear equations.

\begin{array}{rcl}
x + 3y + 0z = 3 \\
0x + 0y + 1z = 2 \\
\end{array}

Hint: these equations are in reduced row echelon form, so there are shortcuts to picking solutions.

In [115]:
# YOUR CHANGES HERE

p10 = (0, 1, 2)

In [116]:
p10

(0, 1, 2)

### Problem 11

Set `p11` to be a tuple or list of the average yields in the vineyard data set for 1989, 1990, and 1991 in that order.

In [117]:
# YOUR CHANGES HERE

p11 = list(vineyard.mean())

In [118]:
p11

[3.2788461538461537, 9.653846153846153, 18.08653846153846]

### Problem 12

Set `p12` to the 95th percentile of the data in `q12`.

In [119]:
# DO NOT CHANGE

q12 = np.array([3.44857705, 2.09151799, 4.98803337, 3.8649001 , 1.20265499,
       3.89903439, 3.05276698, 0.92826333, 3.20371215, 1.81124845,
       3.53150155, 2.32418747, 1.81826697, 3.50670706, 1.37181554,
       2.95770001, 3.80008758, 2.65923837, 2.83248683, 2.91306525,
       2.18314379, 2.17931002, 2.9086665 , 3.26098354, 3.24755896,
       1.01129371, 4.56540725, 3.05517241, 2.32079938, 3.39392893,
       3.3886077 , 3.38112083, 3.88523072, 3.13214221, 3.73298754,
       4.11129171, 2.74133096, 2.4825709 , 3.21885293, 4.08327916,
       2.82768517, 2.1188981 , 3.45886466, 4.20440619, 2.25038228,
       1.59150786, 2.24486543, 3.49914959, 3.72254599, 1.84068517])

In [120]:
# YOUR ANSWER HERE

p12 = np.percentile(q12, 95)

In [121]:
p12

4.162504674

### Problem 13

Set `p13` to the average $L_1$ loss using the average of 1989 and 1990 vineyard yields per row to predict 1991 yields per row.

In [122]:
# YOUR CHANGES HERE

# mean of 1989 and 1990 to predict 1991
# use axis=1 to compute mean across columns for each row
mean_inputs = vineyard_inputs[["lugs_1989", "lugs_1990"]].mean(axis=1)

# average L1 loss 
p13 = np.mean(np.abs(mean_inputs - vineyard_target))

In [123]:
p13

11.620192307692308

### Problem 14

Build a linear regression trained with `vineyard_inputs` as its input and `vineyard_target` as its target output. Set `p14` as the output of that regression with `vineyard_inputs` as its input.

In [124]:
# YOUR CHANGES HERE

vineyard_regression = sklearn.linear_model.LinearRegression()
vineyard_regression.fit(vineyard_inputs, vineyard_target)
p14 = vineyard_regression.predict(vineyard_inputs)

In [125]:
p14

array([12.46642263, 16.68370318, 18.66216936, 17.34319191, 19.91175065,
       18.56238423, 19.32165808, 19.68179142, 21.2307281 , 20.24149501,
       22.02039093, 20.24149501, 19.45183218, 21.3609022 , 20.90098374,
       22.58009452, 20.11132091, 22.67987965, 19.65140244, 23.33936837,
       20.90098374, 24.25920531, 20.34128014, 21.100554  , 19.78157655,
       23.89907197, 20.44106527, 22.87944991, 18.00268063, 22.77966478,
       16.68370318, 15.23455163, 15.56429599, 15.56429599, 14.90480727,
       18.00268063, 14.90480727, 16.88327344, 15.56429599, 16.88327344,
       16.22378472, 16.32356985, 15.0045924 , 16.98305857, 15.76386625,
       13.78540008, 12.46642263, 13.78540008, 13.88518521, 12.56620776,
       12.99573725,  9.69829362])

### Problem 15

Given the following data, set `p15` to the weighted variance of 

| Color | Shape | Score | Probability |
|---|---|---|---:|
| red | square | 3 | 0.250 |
| blue | circle | 4 | 0.125 |
| purple | line | 2 | 0.125 |
| purple | diamond | 5 | 0.25 |
| blue | triangle | 3 | 0.25 |

In [126]:
# YOUR CHANGES HERE

# scores and probabilities 
scores = np.array([3, 4, 2, 5, 3])
probabilities = np.array([0.25, 0.125, 0.125, 0.25, 0.25])

# weighted mean
weighted_mean = np.sum(scores * probabilities)

# weighted variance = sum p_i * (x_i - mu)^2
p15 = float(np.sum(probabilities * (scores - weighted_mean) ** 2))

In [127]:
p15

1.0

### Problem 16

Set `p16` to be the correlation between the 1989 and 1990 yields in the vineyard data set.

In [128]:
# YOUR CHANGES HERE

p16 = np.corrcoef(vineyard_inputs["lugs_1989"], vineyard_inputs["lugs_1990"])[0, 1]

In [129]:
p16

0.7224792530209387

### Problem 17

Compute the sample mean and variance of the 1990 vineyard yields.
Assuming that the yields follow a normal distribution with your computed parameters, what would the one-sided p-value of a yield of 13 lugs be?

Hint: use the [SciPy stats module](https://docs.scipy.org/doc/scipy/reference/stats.html) to calculate the p-values from the distribution.

In [133]:
# YOUR CHANGES HERE

# calculate sample mean, variance, and standard deviation
sample_mean = np.mean(vineyard_inputs["lugs_1990"])
sample_var = np.var(vineyard_inputs["lugs_1990"], ddof=1)
sample_std = np.sqrt(sample_var)

# one-sided p-value 
p17 = scipy.stats.norm.sf(13, loc=sample_mean, scale=sample_std)

In [134]:
p17

0.07618255849601964

### Problem 18

Set `p18` to be the $2 \times 3$ matrix full of question marks below, filled in with the following information.
1. Each serving of noodles requires 1/2 cup of flour.
2. Each serving of noodles requires 1/8 cup of water.
3. Noodles do not need sugar.
4. Each serving of cake requires 1/4 cup of flour.
5. Each serving of cake requires 1/4 cup of sugar.
6. Cake does not need water.

\begin{array}{rcl}
\begin{bmatrix}
\text{servings of noodles} & \text{pieces of cake} \\
\end{bmatrix}
\begin{bmatrix}
\text{??} & \text{??} & \text{??} \\
\text{??} & \text{??} & \text{??} \\
\end{bmatrix}
& = &
\begin{bmatrix}
\text{flour needed} & \text{sugar needed} & \text{water needed} \\
\end{bmatrix}
\end{array}

In [132]:
# YOUR CHANGES HERE

[]
# serving of noodle * ?? + pieces of cake * ?? = flour needed
p18 = np.array([[, , ], [, , ], [, , ]])

SyntaxError: invalid syntax (866069374.py, line 5)

In [ ]:
p18

Ellipsis

### Problem 19

Set `p19` to be the cosine similarity of the vectors `x19` and `y19`.

In [ ]:
# DO NOT CHANGE

x19 = [0.4, 0.2, -0.5]
x19

[0.4, 0.2, -0.5]

In [ ]:
# DO NOT CHANGE

y19 = [-0.3, -0.2, 0.4]
y19

[-0.3, -0.2, 0.4]

In [ ]:
# YOUR CHANGES HERE

# use cosine_similarty([vector1], [vector2])
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity([x19], [y19])
p19 = similarity[0, 0]

In [ ]:
p19

-0.9965457582448795

### Problem 20

Set `p20` to the reduced row echelon form of `q20`.

In [ ]:
# DO NOT CHANGE

q20 = np.array([[2., 5., -3., 2.0],
                [-2, 1, 3, -2],
                [ 4.,  1.,  0., 16.]])

In [ ]:
# YOUR CHANGES HERE

p20 = np.array([[1., 0., 0., 4.0],[0, 1, 0, 0], [0., 0., 1., 2.0]])

In [ ]:
p20

array([[1., 0., 0., 4.],
       [0., 1., 0., 0.],
       [0., 0., 1., 2.]])

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR CHANGES HERE